sonar.projectKey=molnarbence-poc-sonarqube-with-python
sonar.organization=molnarbence


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=poc-sonarqube-with-python
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app
sonar.exclusions=**/__pycache__/**

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Language and version
sonar.language=python
sonar.python.version=3.14

# Tests & coverage
sonar.tests=tests
sonar.python.coverage.reportPaths=build/coverage.xml
sonar.coverage.exclusions=tests/**
