name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.14]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        run: make install-dev

      - name: Lint
        run: make lint

      - name: Coverage
        run: make coverage
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true